version: '3.7'

services:
  minecraft-hydra:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 16, 14, 12
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ..:/workspace:cached
      - mincraft-data:/minecraftdata
    container_name: nodehydra
    environment:
    # Need to make sure the below Vars are also set in the /mongodb/createDatabase.js script as currently there is no way to read environment vars with out spawning shell scripts
      ME_CONFIG_MONGODB_ADMINUSERNAME: "Minecraft-Hydra"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "MinecraftGood"
      ME_CONFIG_MONGODB_URL: "mongodb://Minecraft-Hydra:MinecraftGood!@mongo:27017/"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    #network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      - mongo
    ports:
      - "49443:49443"
      - "49080:49080"
    networks:
      - express-mongo
  
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: hydra_minecraft
    restart: unless-stopped
    volumes:
      - mincraft-data:/data
    environment:
      ENABLE_QUERY: "true"
      OPS: "TemporaryWolf"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "notagoodpassword"
      EULA: "TRUE"
      sync-chunk-writes: "false"
      TYPE: "SPIGOT"
      VERSION: "1.16.5"
      MEMORY: "8G"
    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - "25565:25565"
    networks:
      - express-mongo

  mongo:
    image: mongo:latest
    container_name: hydra_mongodb
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - ../mongodb/createDatabase.js:/docker-entrypoint-initdb.d/createDatabase.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "R00tUs3r0nly!"
      MONGO_INITDB_DATABASE: "admin"

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - "27017:27017"
    networks:
      - express-mongo

volumes: 
  mongo-data:
  mincraft-data:
networks:
  express-mongo: